name: WorkflowTestDavid
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    
    steps:
      - name: Print Push
        if: github.event_name == 'push'
        run: |
          echo "This was a push"
          echo "${{ github.event.commits[0].author.name }}"
          echo "${{ github.event.commits[0].message }}"

      - name: Print PR
        if: github.event_name == 'pull_request'
        run: |
          echo "This was a pull request"
          echo "Event number: ${{ github.event.number }}"
          echo "Action run by: ${{ github.actor }}"
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

      - name: Print Manual
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "This was manually started"
          echo "Started by: ${{ github.actor }}"
          echo "Input is ${{ github.event.inputs.level }}, "
          
      - name: Print GitHub context
        run: echo "${{ toJSON(github) }}"
        
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .Net
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build Solution
        run: dotnet build ShoppingList.sln

      - name: BuildSuccess
        if: success()
        run: echo "Build successful" 

      - name: Test
        run: dotnet test

      - name: RunTestSuccessfully
        if: success()
        run: echo "Tests ran successfully" 

      - name: Print matrix values
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using .NET version: ${{ matrix.version }}"
