name: WorkflowTest
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    
    steps:
      - name: Print GitHub context
        run: echo "${{ toJSON(github) }}"
        
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .Net
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build Solution
        run: dotnet build ShoppingList.sln

      - name: BuildSuccess
        if: success()
        run: echo "Build successful" 

      - name: Test
        run: dotnet test

      - name: RunTestSuccessfully
        if: success()
        run: echo "Tests ran successfully" 

      - name: Print matrix values
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using .NET version: ${{ matrix.version }}"
          
      
          
      
