name: WorkflowTest
  
on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Ange ett nivåvärde'
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    
    steps:
      - name: Print Push
        if: github.event_name == 'push'
        run: |
          echo "This was a push"
          echo "${{ github.event.commits[0].author.name }}"
          echo "${{ github.event.commits[0].message }}"

      - name: Print PR
        if: github.event_name == 'pull_request'
        run: |
          echo "This was a pull request"
          echo "Event number: ${{ github.event.number }}"
          echo "Action run by: ${{ github.actor }}"
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

      - name: Print Manual
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "This was manually started"
          echo "Started by: ${{ github.actor }}"
          echo "Input is ${{ github.event.inputs.level }}, "
        
      - name: Print GitHub context
        run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.commits[0].author.name }}"
          echo "${{ github.event.commits[0].message }}"
          echo "${{ toJSON(github) }}"
          
